### ISSUE TITLE
Getting 'Object reference not set to an instance of an object.' exception

### ISSUE THREAD

**Issue by terryaney** [Giorgi/LINQPad.QueryPlanVisualizer#4]
I have a compiled context doing a simple query:

`Profiles.Where( p => p.Client.cName == "AnnArbor" ).DumpPlan();`

And it throws the exception.  Not much information in the exception.  Let me know what other information I can provide to help.

Trace:

>    at ExecutionPlanVisualizer.QueryPlanVisualizer.DumpPlan[T](IQueryable`1 queryable, Boolean dumpData)
>    at UserQuery
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

**Comment by terryaney** [comment]
Hmm, seems to work against the dynamically created context from LINQPad against same DB/table.  Are compiled contexts supported?

**Comment by borislitvak** [comment]
I can also report the above behavior on v4.57.02.
Did not check the dynamically created context part.

**Comment by Giorgi** [comment]
@terryaney @borislitvak Do you use LINQ to SQL or Entity Framework typed data context?

**Comment by terryaney** [comment]
I use LINQ to SQL…I see you just made EF work on another comment.  But I know we have code for our L2S stuff that leverages a DbContextInterceptor (or whatever it is called) so hopefully you can find that available to you as well.

**Comment by Giorgi** [comment]
@terryaney I don't remember any class which is able to intercept LINQ to SQL queries. I will see what I can do to make it work.

**Comment by Giorgi** [comment]
This should be fixed now. Will publish a new release tomorrow.

**Comment by borislitvak** [comment]
I am still having the same issue with LINQ to Entities, as this tool only supports EF6 contexts.
This is the reason the LinqPad created context words.
Is there any way to make the tool work for EF5?

**Comment by Giorgi** [comment]
@borislitvak Can you create a test data context dll and attach it to this issue?
